[[redirects]]
  from = "https://grupozap-code-challenge.s3-website-us-east-1.amazonaws.com/*"
  to = "http://grupozap-code-challenge.s3-website-us-east-1.amazonaws.com/*"
  status = 200
  force = true
